# The docker-compose.yml file is __only__ used for local development.
# This means that changes to this file will not affect cloud deployments in any way.
# Read more at https://docs.divio.com/reference/docker-docker-compose/
services:
  web:
    build: .
    ports:
      - '8000:80'
    volumes:
      - '.:/app:rw'
      - './data:/data:rw'
      - 'node_modules:/app/node_modules'
    # We are using the .env file to store environment variables locally.
    env_file: '.env'
    links:
      - 'database_default'
    # The following command is used to start the local development server.
    # Removing this line will mimic the deployment behaviour on Divio Cloud.
    command: 'npm run develop'

  database_default:
    image: postgres:15.7-alpine
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      SERVICE_MANAGER: 'fsm-postgres'
    volumes:
      - '.:/app:rw'
      - 'database-default:/var/lib/postgresql/data/'

volumes:
  node_modules:
  database-default:
